### ISSUE TITLE
Crash on switching to canvas only mode (win10)

### ISSUE THREAD

**Issue by wojtryb** [wojtryb/kritaSubwindowOrganizer#3]
when I switch to canvas only mode some times with the tab key something fails, I get an error message and after closing that message Krita closes.

Traceback (most recent call last):
  File "C:\Users\Dannel\AppData\Roaming\krita\pykrita\subwindowOrganizer\mdiAreaFilter.py", line 17, in eventFilter
    self.resizer.moveSubwindows()
  File "C:\Users\Dannel\AppData\Roaming\krita\pykrita\subwindowOrganizer\resizer.py", line 98, in moveSubwindows
    self.otherSubwin.resize(self.otherSize)
AttributeError: 'NoneType' object has no attribute 'resize'

**Comment by wojtryb** [comment]
Confirmed once on linux too. Followed by the next traceback:
Traceback (most recent call last):
  File "/home/wojtryb/.local/share/krita/pykrita/subwindowOrganizer/mdiAreaFilter.py", line 25, in eventFilter
    self.viewOpenedEvent(self.resizer)
  File "/home/wojtryb/.local/share/krita/pykrita/subwindowOrganizer/mdiAreaFilter.py", line 101, in viewOpenedEvent
    self.resizer.userModeSplit()
  File "/home/wojtryb/.local/share/krita/pykrita/subwindowOrganizer/resizer.py", line 181, in userModeSplit
    self.toggleAlwaysOnTop(self.otherSubwin, False)
  File "/home/wojtryb/.local/share/krita/pykrita/subwindowOrganizer/resizer.py", line 40, in toggleAlwaysOnTop
    menu = subwindow.children()[0]
AttributeError: 'NoneType' object has no attribute 'children'
